# Generated by Django 5.1.3 on 2024-11-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_invoice_date_alter_invoicedetail_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='customer_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='InvoiceDetail',
        ),
    ]
